{
 "title": "System Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "val_job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "val_host",
    "label": "Host",
    "query": "label_values(node_uname_info{job=\"$val_job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "전체 모니터링", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "#$val_job 메모리 사용률",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{job=\"$val_job\"}[1m]) + avg_over_time(node_memory_Cached_bytes{job=\"$val_job\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{job=\"$val_job\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{job=\"$val_job\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "#$val_job CPU 사용률",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"$val_job\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "#$val_job 디스크 사용률",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (100 * ((node_filesystem_avail_bytes{job=\"$val_job\"})  / (node_filesystem_size_bytes{job=\"$val_job\"})))",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "#$val_job 아이노드 사용률",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_files_free{job=\"$val_job\"}) / (node_filesystem_files{job=\"$val_job\"}) * 100)",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "#$val_job 파일시스템 ReadOnly / Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_readonly{job=\"$val_job\",device!~'rootfs'}",
     "legendFormat": "{{instance}}-{{mountpoint}} -ReadOnly"
    },
    {
     "expr": "node_filesystem_device_error{job=\"$val_job\",device!~'rootfs',fstype!~'tmpfs'}",
     "legendFormat": "{{instance}}-{{mountpoint}} -Error"
    }
   ]
  },
  { "title": "개별 모니터링", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  { "title": "Host", "type": "text", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 }, "content": "---\n# $val_host\n\n\n\n" },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$val_host\",job=\"$val_job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Load Average (5m)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_load5{instance=\"$val_host\",job=\"$val_job\"}"
    }
   ]
  },
  {
   "title": "CPU사용률",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"$val_host\", job=\"$val_job\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "메모리 사용률",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m]) + avg_over_time(node_memory_Cached_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m])))"
    }
   ]
  },
  {
   "title": "Swap 사용률",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 34 },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$val_host\",job=\"$val_job\"} - node_memory_SwapFree_bytes{instance=\"$val_host\",job=\"$val_job\"}) / (node_memory_SwapTotal_bytes{instance=\"$val_host\",job=\"$val_job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$val_host\",job=\"$val_job\"} - node_boot_time_seconds{instance=\"$val_host\",job=\"$val_job\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 38 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$val_host\",job=\"$val_job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 38 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$val_host\",job=\"$val_job\"}"
    }
   ]
  },
  {
   "title": "CPU 사용률",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"$val_host\", job=\"$val_job\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "메모리 사용량",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m])",
     "legendFormat": "{{instance}}-Total"
    },
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m]) - (avg_over_time(node_memory_MemFree_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m]) + avg_over_time(node_memory_Cached_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m]))",
     "legendFormat": "{{instance}}-Used"
    },
    {
     "expr": "avg_over_time(node_memory_MemFree_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m]) + avg_over_time(node_memory_Cached_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{instance=\"$val_host\", job=\"$val_job\"}[1m])",
     "legendFormat": "{{instance}}-Free"
    }
   ]
  },
  {
   "title": "디스크 잔여량",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$val_host\", job=\"$val_job\"}",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "아이노드 잔여량",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files_free{instance=\"$val_host\", job=\"$val_job\"}",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "디스크 R/W 데이터량",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "Bps", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$val_host\",job=\"$val_job\"}[5m])",
     "legendFormat": "{{device}} - Reads"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$val_host\",job=\"$val_job\"}[5m])",
     "legendFormat": "{{device}} - Writes"
    }
   ]
  },
  {
   "title": "디스크 IOps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$val_host\",job=\"$val_job\"}[5m])",
     "legendFormat": "{{device}} - Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$val_host\",job=\"$val_job\"}[5m])",
     "legendFormat": "{{device}} - Writes"
    }
   ]
  },
  {
   "title": "하드웨어 온도",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$val_host\",job=\"$val_job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} 온도"
    }
   ]
  },
  {
   "title": "파일 시스템 ReadOnly / Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_readonly{instance=\"$val_host\",job=\"$val_job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} -ReadOnly"
    },
    {
     "expr": "node_filesystem_device_error{instance=\"$val_host\",job=\"$val_job\",device!~'rootfs',fstype!~'tmpfs'}",
     "legendFormat": "{{mountpoint}} -Error"
    }
   ]
  },
  {
   "title": "네트워크 트래픽",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "bps", "label": "bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$val_host\",job=\"$val_job\"}[5m])*8",
     "legendFormat": "{{device}} - In"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$val_host\",job=\"$val_job\"}[5m])*8",
     "legendFormat": "{{device}} - Out"
    }
   ]
  }
 ]
}